exam10/Models/User.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace exam10.Models
{
    public class User
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

exam10/ViewModels/HomeVM.cs
using exam10.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace exam10.ViewModels
{
    public class HomeVM
    {
        public List<User> users { get; set; }
    }
}

exam10/Areas/Manage/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace exam10.Areas.Manage.Controllers
{
    [Area("Manage")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

exam10/Areas/Manage/Controllers/UserController.cs
using exam10.DAL;
using exam10.Models;
using exam10.Utilies;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace exam10.Areas.Manage.Controllers
{
    [Area("Manage")]
    public class UserController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        public UserController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;

        }
        public async Task< IActionResult> Index()
        {
            List<User> users = await _context.users.ToListAsync();
            return View(users);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult> Create(User user)
        {
            if (!ModelState.IsValid) return View();
            bool IsExist = _context.users.Any(s => s.Title.ToLower().Trim() == user.Title.ToLower().Trim());
            if (IsExist) return View();
            user.Image = await user.Photo.SaveFileAsync(Path.Combine(_env.WebRootPath, "assets", "img"));
            await _context.users.AddAsync(user);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int id)
        {
            User user = _context.users.Find(id);
            if (user == null) return NotFound();
            

            FileExtension.DeleteFile(Path.Combine(_env.WebRootPath, "assets", "img", user.Image));
            _context.users.Remove(user);
            _context.SaveChanges();
            
            return RedirectToAction(nameof(Index));

        }
        
        public IActionResult Update(int id)
        {
            User user = _context.users.Find(id);
            if (user == null) return NotFound();
            return View(user);


        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id,User user)
        {
            if (user.Id != id) return BadRequest();
            User useritem = _context.users.Find(id);
            if (useritem == null) return NotFound();
            useritem.Title = user.Title;
            useritem.FullName = user.FullName;
            useritem.Image = user.Image;
            useritem.Position = user.Position;
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));


        }

    }
}

exam10/Controllers/HomeController.cs
using exam10.DAL;
using exam10.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace exam10.Controllers
{
    public class HomeController : Controller
    {

        private AppDbContext _context { get; }
        public HomeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task< IActionResult> Index()
        {
            HomeVM homeVM = new HomeVM()
            {
                users = await _context.users.ToListAsync(),
            };
            return View(homeVM);
        }


        

       
    }
}

exam10/Views/Home/Index.cshtml
@model HomeVM


@{
    ViewData["Title"] = "Home Page";
}
<main>
    <!-- Product -->
    <section class="product">
        <div class="container">
            <div class="row">
                <div class="col-md-4 mt-5 product-box">
                    <div class="icon-box">
                        <i class="fa-solid fa-tags"></i>
                    </div>
                    <div class="description-box">
                        <h4>Showcase Your App</h4>
                        <p>
                            Showcase your app in style with this professional looking
                            template.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 mt-5 product-box">
                    <div class="icon-box">
                        <i class="fa-solid fa-tags"></i>
                    </div>
                    <div class="description-box">
                        <h4>Showcase Your App</h4>
                        <p>
                            Showcase your app in style with this professional looking
                            template.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 mt-5 product-box">
                    <div class="icon-box">
                        <i class="fa-solid fa-tags"></i>
                    </div>
                    <div class="description-box">
                        <h4>Showcase Your App</h4>
                        <p>
                            Showcase your app in style with this professional looking
                            template.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 mt-5 product-box">
                    <div class="icon-box">
                        <i class="fa-solid fa-tags"></i>
                    </div>
                    <div class="description-box">
                        <h4>Showcase Your App</h4>
                        <p>
                            Showcase your app in style with this professional looking
                            template.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 mt-5 product-box">
                    <div class="icon-box">
                        <i class="fa-solid fa-tags"></i>
                    </div>
                    <div class="description-box">
                        <h4>Showcase Your App</h4>
                        <p>
                            Showcase your app in style with this professional looking
                            template.
                        </p>
                    </div>
                </div>
                <div class="col-md-4 mt-5 product-box">
                    <div class="icon-box">
                        <i class="fa-solid fa-tags"></i>
                    </div>
                    <div class="description-box">
                        <h4>Showcase Your App</h4>
                        <p>
                            Showcase your app in style with this professional looking
                            template.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Info -->
    <section class="info">
        <div class="container">
            <div class="row">
                <div class="col-md-5 img-left">
                    <img src="~/assets/img/2.jpg" alt="" />
                </div>
                <div class="col-md-7 info-description">
                    <h1>
                        Awesome App
                        <br />
                        App Landing Template
                    </h1>
                    <p class="">
                        An awesome landing page template to showcase your app features,
                        screenshots, pricing, user testimonials and download links.
                        <br />
                        <br />
                        <br />

                        Re-establish the main use case of your app by listing them
                        below. Make sure to place a relavent screenshot on the left.
                    </p>
                    <ul>
                        <li>
                            <i class="fa-solid fa-check"></i> Amazing Design to Present
                            Your App
                        </li>
                        <li>
                            <i class="fa-solid fa-check"></i> Fully Responsive and Powered
                            by Bootstrap & PaperKit
                        </li>
                        <li>
                            <i class="fa-solid fa-check"></i>Very Easy to Customize and
                            Setup
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!-- Screenshot -->
    <section class="screen">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <h1>Take a look at our screenshots</h1>
                    <br />
                    <br />

                    <p class="w-50 mx-auto">
                        Add your app screenshots below. Make sure to make them lively by
                        putting them inside real device mockups Replace this text to
                        describe the screenshots of your app.
                    </p>
                </div>
                <div class="row">
                    <div class="col-md-12 mt-5">
                        <div class="swiper mySwiper">
                            <div class="swiper-wrapper">
                                <div class="swiper-slide">
                                    <img src="~/assets/img/3.jpg" alt="" />
                                </div>
                                <div class="swiper-slide">
                                    <img src="~/assets/img/4.jpg" alt="" />
                                </div>

                                <div class="swiper-slide">
                                    <img src="~/assets/img/5.jpg" alt="" />
                                </div>
                            </div>
                            <div class="swiper-button-next"></div>
                            <div class="swiper-button-prev"></div>
                            <div class="swiper-pagination"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Package -->
    <section class="package">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center mt-5  mx-auto">
                    <h1>
                        We've got the perfect package for you
                    </h1>
                    <br>

                    <p class="w-50 mx-auto">
                        A section to display your pricing structure. Make sure to highlight your most popular plan like shown below.
                        Replace this text to describe your pricing plan.
                    </p>
                </div>

            </div>
            <div class="row">
                <div class="col-md-3 card-box">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">

                            <h5 class="card-title">Special title treatment</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <span>$12.0/m</span>
                            <ul>
                                <li>One User</li>
                                <li>Multiple Access</li>
                                <li>SMS Support</li>
                                <li>24/7 Online Support</li>
                            </ul>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 card-box">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">

                            <h5 class="card-title">Special title treatment</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <span>$12.0/m</span>
                            <ul>
                                <li>One User</li>
                                <li>Multiple Access</li>
                                <li>SMS Support</li>
                                <li>24/7 Online Support</li>
                            </ul>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 card-box">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">

                            <h5 class="card-title">Special title treatment</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <span>$12.0/m</span>
                            <ul>
                                <li>One User</li>
                                <li>Multiple Access</li>
                                <li>SMS Support</li>
                                <li>24/7 Online Support</li>
                            </ul>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 card-box">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">

                            <h5 class="card-title">Special title treatment</h5>
                            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
                            <span>$12.0/m</span>
                            <ul>
                                <li>One User</li>
                                <li>Multiple Access</li>
                                <li>SMS Support</li>
                                <li>24/7 Online Support</li>
                            </ul>
                            <a href="#" class="btn btn-primary">Go somewhere</a>
                        </div>
                    </div>
                </div>




            </div>
        </div>
    </section>
    <!-- Customer -->
    <section class="customer">
        <div class="container">
            <div class="row">
                <div class="col-md-12 mt-5 text-center mx-auto">
                    <h1>What our customers are saying</h1>
                    <br>
                    <p class="w-50 mx-auto">
                        Real user testimonials are great way to attract new customers and increase their trust into using your app.
                        Replace the testimonials below with the ones for your own app.
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="box-div d-flex ">
                    @foreach (var item in Model.users)
                    {
                    <div class="col-md-4  title-box">
                        <div class="title">
                            <p>@item.Title</p>
                        </div>
                        <div class="row pt-3">
                            <div class="col-md-5 img-user">
                                <img src="~/assets/img/@item.Image" alt="">
                            </div>
                            <div class="col-md-7 pt-3">
                                <h5>@item.FullName</h5>
                                <p>@item.Position</p>
                            </div>
                        </div>
                    </div>

                    }

                   
                </div>
            </div>

        </div>

    </section>
</main>

exam10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- Css -->
    <link rel="stylesheet" href="~/assets/css/main.css" />
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />
</head>
<!-- FontAvesome -->
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
      integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer" />
<!-- Swiper -->
<link rel="stylesheet"
      href="https://unpkg.com/swiper/swiper-bundle.min.css" />

<body>
    <!-- Header -->
    <header>
        <div class="header-nav">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    <a class="navbar-brand text-center" asp-controller="Dashboard" asp-action="Index" asp-area="Manage"><img src="./assets/img/logo.png" alt="" /> AVESOME APP</a>
                    <button class="navbar-toggler"
                            type="button"
                            data-bs-toggle="collapse"
                            data-bs-target="#navbarNavAltMarkup"
                            aria-controls="navbarNavAltMarkup"
                            aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                        <div class="navbar-nav ms-auto">
                            <a class="nav-link" href="#">Home</a>
                            <a class="nav-link" href="#">Features</a>
                            <a class="nav-link" href="#">Pricing</a>
                            <a class="nav-link" href="#">Downlad Now</a>
                        </div>
                    </div>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="text-box w-50">
                            <h1>
                                Awesome App
                                <br />
                                App Landing Template
                            </h1>
                            <p class="">
                                An awesome landing page template to showcase your app
                                features, screenshots, pricing, user testimonials and download
                                links.
                            </p>
                            <ul>
                                <li>Amazing Design to Present Your App</li>
                                <li>Fully Responsive and Powered by Bootstrap & PaperKit</li>
                                <li>Very Easy to Customize and Setup</li>
                            </ul>
                            <a href="" class="btn">Start Exploring</a>
                        </div>
                    </div>
                    <div class="col-md-6 img-box">
                        <img src="/assets/img/1.jpg" alt="" />
                    </div>
                </div>
            </div>
        </div>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <footer></footer>
    <script src="https://unpkg.com/swiper/swiper-bundle.min.js"></script>

    <script src="~/assets/js/main.js"></script>
</body>
</html>